name: pr

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [stable, nightly]
        luaVersion: ["luajit-openresty"]
        # include:
        # - os: "windows-latest"
        #   toolchain: "msvc"
        #   luaVersion: "luajit-openresty"
        #   neovim: "nightly"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }} - Lua: ${{ matrix.luaVersion }}"

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    - name: Setup MSVC
      # the 'luarocks/gh-actions-lua' step requires msvc to build PUC-Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Lua
      uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "${{ matrix.luaVersion }}"

    - name: Install LuaRocks
      uses: luarocks/gh-actions-luarocks@master

    - name: Build Test Dependencies
      run: |
        luarocks install vusted

    - name: Test
      run: |
        make test
